FOR reg IN TipoExclusion  LOOP
  IF reg.tipo_exclusion = 1 THEN
      DELETE FROM ODS_TRIBUTARIO.#GLOBAL.VAR_TABLA
      WHERE PERIODO = TRUNC(TO_DATE('#GLOBAL.VAR_PERIODO','YYYYMMDD'),'MM')
      AND #GENERACION_REPORTE_EXOGENA.VAR_CAMPO_PRODUCTO IN
      (SELECT TO_NUMBER(NUMERO_PRODUCTO) FROM STG_TRIBUTARIO.stg_fraudes_suplantacion TABLA_FRAUDES WHERE TABLA_FRAUDES.TIPO_EXCLUSION = '1'
		 AND TABLA_FRAUDES.NOMBRE_TABLA  = '#GLOBAL.VAR_TABLA'
      );
     COMMIT;
   ELSIF reg.tipo_exclusion = 3 THEN
      DELETE FROM ODS_TRIBUTARIO.#GLOBAL.VAR_TABLA
      WHERE PERIODO = TRUNC(TO_DATE('#GLOBAL.VAR_PERIODO','YYYYMMDD'),'MM')
      AND NUMERO_ID IN (
      SELECT TABLA_ODS.NUMERO_ID FROM ODS_TRIBUTARIO.#GLOBAL.VAR_TABLA TABLA_ODS inner join (STG_TRIBUTARIO.STG_EXO_PAR_HOMOLOGACION HOMO
      inner join STG_TRIBUTARIO.STG_FRAUDES_SUPLANTACION TABLA_FRAUDES
        ON(HOMO.CODIGO_DAVIVIENDA = TABLA_FRAUDES.TIPO_ID)
        )
        ON(TABLA_ODS.TIPO_ID = HOMO.CODIGO_DIAN
        AND TABLA_ODS.NUMERO_ID = TO_NUMBER(TABLA_FRAUDES.NUMERO_ID)
        )
        WHERE TABLA_ODS.PERIODO = TRUNC(TO_DATE('#GLOBAL.VAR_PERIODO','YYYYMMDD'),'MM')
        AND HOMO.GRUPO_CLASIFICACION = 'TIPO IDENTIFICACION'
        AND HOMO.ORIGEN_INFORMACION = 'CLIENTE360'
        AND TABLA_FRAUDES.TIPO_EXCLUSION = '3' 
		AND TABLA_FRAUDES.NOMBRE_TABLA  = '#GLOBAL.VAR_TABLA'
        );
      COMMIT;
  END IF;
  END LOOP;
END;  


-- Nueva Propuesta IA: 

DELETE FROM ODS_TRIBUTARIO.#GLOBAL.VAR_TABLA T
WHERE T.PERIODO = TRUNC(TO_DATE('#GLOBAL.VAR_PERIODO','YYYYMMDD'),'MM')
  AND EXISTS (
      SELECT 1
      FROM STG_TRIBUTARIO.STG_FRAUDES_SUPLANTACION F
      WHERE F.NOMBRE_TABLA = '#GLOBAL.VAR_TABLA'
        AND (
             /* ============================= */
             /* Tipo de exclusión por PRODUCTO */
             /* ============================= */
             ( F.TIPO_EXCLUSION = '1'
               AND T.#GENERACION_REPORTE_EXOGENA.VAR_CAMPO_PRODUCTO =
                   TO_NUMBER(F.NUMERO_PRODUCTO)
             )

          OR /* ================================ */
             /* Tipo de exclusión por IDENTIFICACIÓN */
             /* ================================ */
             ( F.TIPO_EXCLUSION = '3'
               AND EXISTS (
                   SELECT 1
                   FROM STG_TRIBUTARIO.STG_EXO_PAR_HOMOLOGACION HOMO
                   WHERE HOMO.CODIGO_DAVIVIENDA = F.TIPO_ID
                     AND HOMO.GRUPO_CLASIFICACION = 'TIPO IDENTIFICACION'
                     AND HOMO.ORIGEN_INFORMACION  = 'CLIENTE360'
                     AND T.TIPO_ID   = HOMO.CODIGO_DIAN
                     AND T.NUMERO_ID = TO_NUMBER(F.NUMERO_ID)
               )
             )
        )
  );

COMMIT;